class dataAPI {
  deleteCard(id) {
    this.data = this.data.filter((el) => el.id !== id)
  }
  editingCard(dataForEditing, id) {
    this.data[this.data.findIndex((el) => el.id === id)] = {
      id: dataForEditing.id,
      filter: dataForEditing.filter,
      brand_name: dataForEditing.value_brand_name,
      card_description: dataForEditing.value_card_description,
      modal_description: dataForEditing.value_modal_description,
      spec_ofer: dataForEditing.value_spec_ofer,
      site_name: dataForEditing.value_site_name,
      duration: dataForEditing.value_duration,
      email: dataForEditing.value_email,
      phone_number: dataForEditing.value_phone_number,
      logo_url: dataForEditing.value_logo_url,
    }
  }
  addCard(dataForAdd) {
    this.data.push({ ...dataForAdd, id: this.dataCounter })
    this.dataCounter++
    console.log(this.data)
  }

  dataCounter = 11
  data = [
    {
      id: 0,
      filter: 'sport',
      brand_name: 'x-fit1',
      card_description: 'Сеть фитнес-клубов',
      modal_description:
        'Можно получить скидки при одновременной покупке двух и более клубных карт. Обратитесь к персональному менеджеру Компании X-Fit Тимуру Максутову и скажите, что вы сотрудник компании Рандеву.',
      spec_ofer: 'Скидка от 35%',
      site_name: 'http://www.xfit.ru',
      duration: 'Без срока',
      email: 'example@mail.ru',
      phone_number: '+7 (903) 203-06-99',
      logo_url: 'http://toplogos.ru/images/logo-gallery.png',
    },
    {
      id: 1,
      filter: 'sport',
      brand_name: 'x-fit2',
      card_description: 'Сеть фитнес-клубов',
      modal_description:
        'Можно получить скидки при одновременной покупке двух и более клубных карт. Обратитесь к персональному менеджеру Компании X-Fit Тимуру Максутову и скажите, что вы сотрудник компании Рандеву.',
      spec_ofer: 'Скидка от 35%',
      site_name: 'http://www.xfit.ru',
      duration: 'Без срока',
      email: 'example@mail.ru',
      phone_number: '+7 (903) 203-06-99',
      logo_url:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Playstation_logo_colour.svg/2560px-Playstation_logo_colour.svg.png',
    },
    {
      id: 2,
      filter: 'beauty',
      brand_name: 'красотка',
      card_description: 'изи',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 3,
      filter: 'beauty',
      brand_name: 'красопетка',
      card_description: 'легко',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 4,
      filter: 'health',
      brand_name: '1',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 5,
      filter: 'health',
      brand_name: '2',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 6,
      filter: 'leisure',
      brand_name: '1',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 7,
      filter: 'leisure',
      brand_name: '2',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 8,
      filter: 'techniq',
      brand_name: '1',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 9,
      filter: 'techniq',
      brand_name: '2',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 10,
      filter: 'other',
      brand_name: '1',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
    {
      id: 11,
      filter: 'other',
      brand_name: '2',
      card_description: '',
      modal_description: '',
      spec_ofer: '',
      site_name: '',
      duration: '',
      email: '',
      phone_number: '',
      logo_url: '',
    },
  ]
}

export default dataAPI
